### ISSUE TITLE
Message appears corrupted or tampered with error

### ISSUE THREAD

**Issue by benv666** [actuallymentor/signer#2]
When signing a message using `frame.sh` in the `brave` browser I got the error message "Message appears corrupted or tampered with` after signing.

What's  interesting is that on the signature request some fields appear to be missing:
![image](https://user-images.githubusercontent.com/165034/180731355-a5c42215-9aed-4a06-82bd-052e92ce99ad.png)

There is also a lof of undefined going on in the debug console:
![image](https://user-images.githubusercontent.com/165034/180731823-03f59090-99e9-4d61-a97d-94d581184913.png)

After hitting the browser's back button at some point it filled out the proper fields:
![image](https://user-images.githubusercontent.com/165034/180731930-0217d46b-4fe6-42fa-ac04-63bf8f24b498.png)
and then it properly signed as well, debug console:
![image](https://user-images.githubusercontent.com/165034/180731965-acbbc699-413b-4545-9aab-243e6b05fa51.png)

Looks like a timing or retry issue to me :)

**Comment by actuallymentor** [comment]
Brave has some weirdness to it. When I get back from travel I'll do a full brave debugging.

**Comment by actuallymentor** [comment]
It should work now, let me know if it does for you!
